CREATE TABLE CUSTOMER (
  CUST_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  F_NAME VARCHAR(255),
  L_NAME VARCHAR(255),
  CONTACT_NO VARCHAR(255),
  C_TYPE VARCHAR(255)
);

CREATE TABLE RENTAL (
  RENTAL_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  STATUS VARCHAR(255),
  START_DATE VARCHAR(255),
  END_DATE VARCHAR(255),
  AMOUNT_DUE INT,
  RENTAL_TYPE VARCHAR(255),
  NO_OF_DAYS INT,
  NO_OF_WEEKS INT,
  C_ID INT,
  V_ID INT,
  FOREIGN KEY(C_ID) REFERENCES CUSTOMER(CUST_ID),
  FOREIGN KEY(V_ID) REFERENCES CAR(VEHICLE_ID)
);

CREATE TABLE CAR (
  VEHICLE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  MODEL VARCHAR(255),
  YEAR INT,
  CATEGORY VARCHAR(255),
  DAILY_RATE INT,
  WEEKLY_RATE INT,
  AVAILABLE VARCHAR(255),
  CAR_TYPE VARCHAR(255),
  OWN_ID INT,
  FOREIGN KEY(OWN_ID) REFERENCES OWNER(OWNER_ID)
)AUTO_INCREMENT=1001;

CREATE TABLE OWNER (
  OWNER_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  OWNER_NAME VARCHAR(255),
  OWNER_TYPE VARCHAR(255)
);

CREATE TABLE BANK (
  B_OWN_ID INT,
  BANK_CODE VARCHAR(255),
  FOREIGN KEY(B_OWN_ID) REFERENCES OWNER(OWNER_ID)
);

CREATE TABLE RENTAL_COMPANY (
  R_OWN_ID INT,
  COMPANY_NAME VARCHAR(255),
  FOREIGN KEY(R_OWN_ID) REFERENCES OWNER(OWNER_ID)
);

CREATE TABLE PERSONAL (
  P_OWN_ID INT,
  SSN VARCHAR(255),
  FOREIGN KEY(P_OWN_ID) REFERENCES OWNER(OWNER_ID)
);


