INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID) VALUES ('Toyota Corolla',2015,'LUXURY',100.00,350.00,'Y','COMPACT',1);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID) VALUES ('Toyota Land Cruiser',2015,'REGULAR',200.00,600.00,'N','MEDIUM',2);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID) VALUES ('Chevrolet Silverado',2014,'REGULAR',200.00,600.00,'Y','LARGE',3);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID) VALUES ('Ford F150',2015,'LUXURY',100.00,300.00,'Y','SUV',4);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID) VALUES ('Dorge Ram1500',2015,'REGULAR',100.00,300.00,'N','TRUCK',5);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID) VALUES ('Honda CRZ',2013,'REGULAR',80.00,400.00,'N','VAN',6);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID) VALUES ('BMW 7 series',2013,'LUXURY',80.00,400.00,'Y','TRUCK',7);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID) VALUES ('Mercedes GL 400',2013,'REGULAR',80.00,400.00,'N','COMPACT',8);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID) VALUES ('Cadillac ATS-V',2015,'LUXURY',200.00,1000.00,'N','LARGE',9);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID) VALUES ('Ford Focus',2014,'REGULAR',150.00,170.00,'Y','COMPACT',10);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID) VALUES ('GMC Canyon',2014,'LUXURY',200.00,600.00,'N','SUV',11);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID) VALUES ('Honda ODYSSEY',2013,'REGULAR',250.00,700.00,'N','COMPACT',12);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID) VALUES ('Toyota RAV4',2013,'LUXURY',110.00,440.00,'Y','TRUCK',13);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID) VALUES ('Audi Q7',2014,'REGULAR',400.00,1600.00,'N','MEDIUM',14);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID) VALUES ('Nissan JUKE',2014,'LUXURY',200.00,900.00,'N','COMPACT',15);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID) VALUES ('Ford Fusion',2014,'REGULAR',300.00,1500.00,'Y','LARGE',1);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID)VALUES ('Nissan Sentra',2013,'REGULAR',250.00,700.00,'N','MEDIUM',2);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID)VALUES ('Dorge Charger',2013,'LUXURY',350.00,1700.00,'Y','TRUCK',3);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID)VALUES ('Nissan Maxima',2014,'LUXURY',420.00,1200.00,'N','COMPACT',4);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID)VALUES ('Toyato Sienna',2013,'REGULAR',100.00,500.00,'Y','LARGE',5);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID)VALUES ('Honda Fit',2015,'REGULAR',100.00,600.00,'N','MEDIUM',6);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID)VALUES ('Honda Xami',2015,'LUXURY',380.00,1150.00,'Y','COMPACT',7);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID)VALUES ('Audi A4',2015,'REGULAR',750.00,2500.00,'N','SUV',8);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID)VALUES ('Nissan Titan',2014,'REGULAR',400.00,1600.00,'N','TRUCK',9);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID) VALUES ('Nissan A4',2013,'LUXURY',250.00,700.00,'Y','COMPACT',10);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID) VALUES ('Dorge Fusion',2013,'REGULAR',350.00,1700.00,'N','LARGE',11);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID) VALUES ('Toyota A4',2015,'LUXURY',750.00,2500.00,'Y','COMPACT',12);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID) VALUES ('Qualis',2014,'REGULAR',400.00,1600.00,'N','SUV',13);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID)VALUES ('Innova',2013,'LUXURY',250.00,700.00,'N','MEDIUM'14);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID) VALUES ('Honda City',2013,'REGULAR',350.00,1700.00,'Y','COMPACT',15);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID)VALUES ('Mazda Miata',2015,'LUXURY',100.00,600.00,'N','TRUCK',1);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID) VALUES ('Tesla Mode S',2015,'REGULAR',380.00,1150.00,'Y','LARGE',2);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID) VALUES ('Porsche 911',2015,'LUXURY',750.00,2500.00,'N','COMPACT',3);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID) VALUES ('Ford Mustang',2014,'REGULAR',400.00,1600.00,'Y','SUV',4);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID) VALUES ('Lexus ES',2013,'LUXURY',250.00,700.00,'N','COMPACT',5);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID) VALUES('Hyundai Elantra',2013,'REGULAR',350.00,1700.00,'Y','MEDIUM',6);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID) VALUES('GMC Sierra',2015,'LUXURY',750.00,2500.00,'N','LARGE',7);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID)VALUES('Bugatti Chiron',2014,'REGULAR',400.00,1600.00,'N','COMPACT'8);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID) VALUES('Kia Sportage',2013,'LUXURY',250.00,700.00,'N','SUV',9);
INSERT INTO CAR (MODEL, YEAR, CATEGORY, DAILY_RATE, WEEKLY_RATE, AVAILABLE, CAR_TYPE, OWN_ID) VALUES('Honda Civic',2013,'LUXURY',350.00,1700.00,'Y','MEDIUM',10);

insert into OWNER (OWNER_NAME, OWNER_TYPE) values('Amy','Bank');
insert into OWNER (OWNER_NAME, OWNER_TYPE) values('Nikki','Bank');
insert into OWNER (OWNER_NAME, OWNER_TYPE) values('Paul','Bank');
insert into OWNER (OWNER_NAME, OWNER_TYPE) values('Kiana','Bank');
insert into OWNER (OWNER_NAME, OWNER_TYPE) values('Moni','Bank');
insert into OWNER (OWNER_NAME, OWNER_TYPE) values('Vids','Personal');
insert into OWNER (OWNER_NAME, OWNER_TYPE) values('Shaq','Personal');
insert into OWNER (OWNER_NAME, OWNER_TYPE) values('Enna','Personal');
insert into OWNER (OWNER_NAME, OWNER_TYPE) values('Miky','Personal');
insert into OWNER (OWNER_NAME, OWNER_TYPE) values('Sandy','Personal');
insert into OWNER (OWNER_NAME, OWNER_TYPE) values('Joni','Rental company');
insert into OWNER (OWNER_NAME, OWNER_TYPE) values('Sid','Rental company');
insert into OWNER (OWNER_NAME, OWNER_TYPE) values('Milli','Rental company');
insert into OWNER (OWNER_NAME, OWNER_TYPE) values('Vini','Rental company');
insert into OWNER (OWNER_NAME, OWNER_TYPE) values('Sushi','Rental company');


INSERT INTO CUSTOMER (F_NAME, L_NAME, CONTACT_NO, C_TYPE) VALUES('A','Patel','817-881-9432','Individual');
INSERT INTO CUSTOMER (F_NAME, L_NAME, CONTACT_NO, C_TYPE) VALUES('M','Solanki','817-881-9440','Business');
INSERT INTO CUSTOMER (F_NAME, L_NAME, CONTACT_NO, C_TYPE) VALUES('V','Desai','817-881-9439','Individual');
INSERT INTO CUSTOMER (F_NAME, L_NAME, CONTACT_NO, C_TYPE) VALUES('A','Doshi','817-881-9459','Business');
INSERT INTO CUSTOMER (F_NAME, L_NAME, CONTACT_NO, C_TYPE) VALUES('K','Sutaria','817-881-9450','Business');
INSERT INTO CUSTOMER (F_NAME, L_NAME, CONTACT_NO, C_TYPE) VALUES('D','Shah','817-881-9348','Individual');
INSERT INTO CUSTOMER (F_NAME, L_NAME, CONTACT_NO, C_TYPE) VALUES('J','Gandhi','817-881-9315','Business');
INSERT INTO CUSTOMER (F_NAME, L_NAME, CONTACT_NO, C_TYPE) VALUES('R','Gadhiya','817-881-8115','Individual');
INSERT INTO CUSTOMER (F_NAME, L_NAME, CONTACT_NO, C_TYPE) VALUES('M','Vaghela','817-881-7115','Business');
INSERT INTO CUSTOMER (F_NAME, L_NAME, CONTACT_NO, C_TYPE) VALUES('D','Darshi','817-881-6115','Individual');
INSERT INTO CUSTOMER (F_NAME, L_NAME, CONTACT_NO, C_TYPE) VALUES('Y','Soni','817-881-9436','Business');
INSERT INTO CUSTOMER (F_NAME, L_NAME, CONTACT_NO, C_TYPE) VALUES('R','Teli','817-881-9436','Business');

INSERT INTO RENTAL (STATUS, START_DATE, END_DATE, AMOUNT_DUE, RENTAL_TYPE, NO_OF_DAYS, NO_OF_WEEKS, C_ID, V_ID) VALUES('active','2015-11-29','2015-11-30',0,'daily',1,0,1,'1001');
INSERT INTO RENTAL (STATUS, START_DATE, END_DATE, AMOUNT_DUE, RENTAL_TYPE, NO_OF_DAYS, NO_OF_WEEKS, C_ID, V_ID) VALUES('scheduled','2015-12-01','2015-12-05',0,'daily',5,0,6,'1015');
INSERT INTO RENTAL (STATUS, START_DATE, END_DATE, AMOUNT_DUE, RENTAL_TYPE, NO_OF_DAYS, NO_OF_WEEKS, C_ID, V_ID) VALUES('active','2015-11-29','2015-12-05',0,'weekly',0,1,4,'1004');
INSERT INTO RENTAL (STATUS, START_DATE, END_DATE, AMOUNT_DUE, RENTAL_TYPE, NO_OF_DAYS, NO_OF_WEEKS, C_ID, V_ID) VALUES('scheduled','2015-12-01','2015-12-09',0,'daily',9,0,8,'1016');
INSERT INTO RENTAL (STATUS, START_DATE, END_DATE, AMOUNT_DUE, RENTAL_TYPE, NO_OF_DAYS, NO_OF_WEEKS, C_ID, V_ID) VALUES('active','2015-11-29','2015-12-16',0,'daily',18,0,10,'1014');
INSERT INTO RENTAL (STATUS, START_DATE, END_DATE, AMOUNT_DUE, RENTAL_TYPE, NO_OF_DAYS, NO_OF_WEEKS, C_ID, V_ID) VALUES('scheduled','2015-12-29','2015-12-30',0,'daily',2,0,8,'1015');
INSERT INTO RENTAL (STATUS, START_DATE, END_DATE, AMOUNT_DUE, RENTAL_TYPE, NO_OF_DAYS, NO_OF_WEEKS, C_ID, V_ID) VALUES('active','2015-11-29','2015-12-10',0,'daily',12,0,9,'1003');
INSERT INTO RENTAL (STATUS, START_DATE, END_DATE, AMOUNT_DUE, RENTAL_TYPE, NO_OF_DAYS, NO_OF_WEEKS, C_ID, V_ID) VALUES('scheduled','2015-12-14','2015-12-15',0,'daily',2,0,4,'1015');
INSERT INTO RENTAL (STATUS, START_DATE, END_DATE, AMOUNT_DUE, RENTAL_TYPE, NO_OF_DAYS, NO_OF_WEEKS, C_ID, V_ID) VALUES('active','2015-11-29','2015-12-10',0,'daily',12,0,11,'1029');
INSERT INTO RENTAL (STATUS, START_DATE, END_DATE, AMOUNT_DUE, RENTAL_TYPE, NO_OF_DAYS, NO_OF_WEEKS, C_ID, V_ID) VALUES('scheduled','2015-12-27','2015-12-30',0,'daily',4,0,7,'1004');

insert into BANK values(1,'SB1001');
insert into BANK values(2,'BOA001');
insert into BANK values(3,'HDFC002');
insert into BANK values(4,'WF0012');
insert into BANK values(5,'AB001');

insert into PERSONAL values(6,'SS12345678');
insert into PERSONAL values(7,'SS87654321');
insert into PERSONAL values(8,'SS21324567');
insert into PERSONAL values(9,'SS32145678');
insert into PERSONAL values(10,'SS33445566');

insert into RENTAL_COMPANY values(11,'Acropolis');
insert into RENTAL_COMPANY values(12,'AndroCarPolis');
insert into RENTAL_COMPANY values(13,'LetsRideIn');
insert into RENTAL_COMPANY values(14,'Ammy');
insert into RENTAL_COMPANY values(15,'DavidCarService');




